### PR TITLE
Record metric labels for repeated tasks.

### LINKED ISSUE #90: RepeatedTask metric labels are incorrect
https://github.com/cashapp/wisp/blob/98ed57db7ef4ed79ef0f2760fe8a127566f54849/wisp-task/src/main/kotlin/wisp/task/RepeatedTaskMetrics.kt#L20 looks like it's trying to add two labels to the metric, `name` and `result`. There are two problems here:
* that `tag` method actually takes `key` and `value` parameters, so we are adding one label named `name` and recording the value `result`
* there's no attempt to pass correct tags when recording the metric in https://github.com/cashapp/wisp/blob/main/wisp-task/src/main/kotlin/wisp/task/RepeatedTask.kt#L108

### PR DESCRIPTION
**Pull request by jdm-square**
Fixes #90.

### CODE REVIEW

File: wisp-task/src/main/kotlin/wisp/task/RepeatedTaskMetrics.kt [hunk 1]
```diff
@@ -14,24 +14,36 @@ import io.micrometer.core.instrument.MeterRegistry
...
-            .tag("name", "result")
+            .tag("name", name)
+            .tag("result", result)
             .percentilePrecision(4)
             .publishPercentiles(0.5, 0.75, 0.95, 0.99, 0.999)
             .publishPercentileHistogram()
             .register(meterRegistry)
 
-    internal var successCount: Counter = Counter.builder("repeated.task.success")
+    internal val successCount: Counter = Counter.builder("repeated.task.success")
```
Comment (staktrace) [inline wisp-task/src/main/kotlin/wisp/task/RepeatedTaskMetrics.kt:31]: Did you mean to use the companion const vals here?

**Review by staktrace — APPROVED** [review]

File: wisp-task/src/main/kotlin/wisp/task/RepeatedTaskMetrics.kt (hunk 1 above)
Comment (jdm-square) [reply wisp-task/src/main/kotlin/wisp/task/RepeatedTaskMetrics.kt:31]: Indeed.
